import React, { useState, useEffect, useCallback } from 'react';
import { useParams } from 'react-router-dom';
import {
  Box,
  Typography,
  Paper,
  Chip,
  Divider,
  Alert,
  CircularProgress,
  Card,
  CardContent
} from '@mui/material';
import { format } from 'date-fns';

import { apiService } from '../services/apiService';

const ReportViewer = () => {
  const { reportId } = useParams();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const loadReport = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const reportData = await apiService.getReport(reportId);
      setReport(reportData);
    } catch (err) {
      console.error('Failed to load report:', err);
      setError('Failed to load report. The report may not exist or may have been removed.');
    } finally {
      setLoading(false);
    }
  }, [reportId]);

  useEffect(() => {
    loadReport();
  }, [reportId, loadReport]);

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}>
        <CircularProgress />
      </Box>
    );
  }

  if (error) {
    return (
      <Alert severity="error" sx={{ mt: 2 }}>
        {error}
      </Alert>
    );
  }

  if (!report) {
    return (
      <Alert severity="info" sx={{ mt: 2 }}>
        Report not found.
      </Alert>
    );
  }

  return (
    <Box>
      {/* Report Header */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="h4" gutterBottom>
          {report.title}
        </Typography>
        
        <Box sx={{ display: 'flex', gap: 1, mb: 2, flexWrap: 'wrap' }}>
          <Chip
            label={`Report #${report.id}`}
            size="small"
            variant="outlined"
          />
          <Chip
            label={report.status}
            size="small"
            color={report.status === 'published' ? 'success' : 'warning'}
          />
          {report.confidence_score && (
            <Chip
              label={`Confidence: ${Math.round(report.confidence_score * 100)}%`}
              size="small"
              color={
                report.confidence_score > 0.7 ? 'success' :
                report.confidence_score > 0.4 ? 'warning' : 'error'
              }
            />
          )}
          <Chip
            label={format(new Date(report.generated_at), 'MMM dd, yyyy HH:mm')}
            size="small"
            variant="outlined"
          />
        </Box>

        {report.ai_model_version && (
          <Typography variant="caption" color="text.secondary">
            Generated by {report.ai_model_version}
          </Typography>
        )}
      </Paper>

      {/* Legal Disclaimer */}
      <Alert severity="warning" sx={{ mb: 3 }}>
        <Typography variant="body2">
          <strong>DISCLAIMER:</strong> This report is AI-generated and for educational purposes only. 
          This is NOT financial advice. Correlations do not imply causation. Always conduct your own 
          research and consult with qualified financial advisors before making investment decisions.
        </Typography>
      </Alert>

      {/* Report Content */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="h6" gutterBottom>
          Analysis Report
        </Typography>
        <Divider sx={{ mb: 2 }} />
        
        <Typography
          variant="body1"
          sx={{
            whiteSpace: 'pre-wrap',
            lineHeight: 1.6,
            fontSize: '1rem'
          }}
        >
          {report.content}
        </Typography>
      </Paper>

      {/* Correlations Found */}
      {report.correlations_found && Object.keys(report.correlations_found).length > 0 && (
        <Card sx={{ mb: 3 }}>
          <CardContent>
            <Typography variant="h6" gutterBottom>
              Correlations Identified
            </Typography>
            <Divider sx={{ mb: 2 }} />
            
            <Box
              sx={{
                backgroundColor: '#f5f5f5',
                p: 2,
                borderRadius: 1,
                fontFamily: 'monospace',
                fontSize: '0.875rem',
                overflow: 'auto'
              }}
            >
              <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>
                {JSON.stringify(report.correlations_found, null, 2)}
              </pre>
            </Box>
          </CardContent>
        </Card>
      )}

      {/* Data Sources */}
      {report.data_sources && Object.keys(report.data_sources).length > 0 && (
        <Card sx={{ mb: 3 }}>
          <CardContent>
            <Typography variant="h6" gutterBottom>
              Data Sources Used
            </Typography>
            <Divider sx={{ mb: 2 }} />
            
            <Box
              sx={{
                backgroundColor: '#f5f5f5',
                p: 2,
                borderRadius: 1,
                fontFamily: 'monospace',
                fontSize: '0.875rem',
                overflow: 'auto'
              }}
            >
              <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>
                {JSON.stringify(report.data_sources, null, 2)}
              </pre>
            </Box>
          </CardContent>
        </Card>
      )}

      {/* Footer Disclaimer */}
      <Alert severity="info">
        <Typography variant="body2">
          This report was generated by Shadow SEC's AI analysis system. Shadow SEC is an open-source 
          financial watchdog project aimed at providing transparent market surveillance. All code, 
          models, and methodologies are publicly available for review and contribution.
        </Typography>
      </Alert>
    </Box>
  );
};

export default ReportViewer;